"use client";

import { useMemo } from "react";
import { motion } from "framer-motion";
import points from "@/data/world-map-points.json";
import pins from "@/data/world-map-pins.json";

// Generated by scripts/generate-world-map.mjs — keep in sync with the viewBox below.
const MAP_WIDTH = 100;
const MAP_HEIGHT = 41.31;

type WorldMapProps = {
  className?: string;
  dotColor?: string;
  activeDotColor?: string;
  /** Fraction of dots that pulse gently, for a "live network" feel. */
  activeRatio?: number;
};

/**
 * Decorative dotted world map rendered from precomputed, normalized
 * points (see scripts/generate-world-map.mjs). Pure SVG + CSS, no
 * runtime dependency on the `dotted-map` country dataset.
 */
export function WorldMap({
  className = "",
  dotColor = "rgba(231, 235, 245, 0.35)",
  activeDotColor = "#4cc9f0",
  activeRatio = 0.05,
}: WorldMapProps) {
  const dots = points as [number, number][];

  const activeIndexes = useMemo(() => {
    const count = Math.floor(dots.length * activeRatio);
    const step = Math.max(1, Math.floor(dots.length / count));
    const set = new Set<number>();
    for (let i = 0; i < count; i++) {
      set.add((i * step + (i % 7)) % dots.length);
    }
    return set;
  }, [dots.length, activeRatio]);

  return (
    <svg
      viewBox={`0 0 ${MAP_WIDTH} ${MAP_HEIGHT}`}
      preserveAspectRatio="xMidYMid meet"
      className={className}
      aria-hidden="true"
    >
      {dots.map(([x, y], i) => {
        const isActive = activeIndexes.has(i);
        return (
          <circle
            key={i}
            cx={x}
            cy={y}
            r={isActive ? 0.42 : 0.32}
            fill={isActive ? activeDotColor : dotColor}
            className={isActive ? "animate-pulse-glow" : undefined}
            style={
              isActive
                ? { animationDelay: `${(i % 20) * 0.15}s`, transformOrigin: `${x}px ${y}px` }
                : undefined
            }
          />
        );
      })}
    </svg>
  );
}

export function WorldMapWithPins({ className = "" }: { className?: string }) {
  return (
    <div className={`relative ${className}`}>
      <WorldMap className="h-full w-full" />
      <svg
        viewBox={`0 0 ${MAP_WIDTH} ${MAP_HEIGHT}`}
        preserveAspectRatio="xMidYMid meet"
        className="absolute inset-0 h-full w-full"
        aria-hidden="true"
      >
        {pins.map((pin, i) => (
          <g key={pin.label}>
            <motion.circle
              cx={pin.x}
              cy={pin.y}
              r={0.9}
              fill="none"
              stroke="#d4af6a"
              strokeWidth={0.15}
              initial={{ opacity: 0.7, scale: 1 }}
              animate={{ opacity: 0, scale: 3.2 }}
              transition={{
                duration: 2.6,
                repeat: Infinity,
                delay: i * 0.35,
                ease: "easeOut",
              }}
              style={{ transformOrigin: `${pin.x}px ${pin.y}px` }}
            />
            <circle cx={pin.x} cy={pin.y} r={0.55} fill="#d4af6a" />
          </g>
        ))}
      </svg>
    </div>
  );
}
